[package]
name = "homework"
version = "1.0.0"
entrypoint = "lib.typ"
authors = ["Daniel Hall <@betapictoris>"]
license = "MIT-0"
description = "Clean and minimalist homework assignment."
repository = "https://github.com/betapictoris/typst-homework"
keywords = ["assignment", "homework", "problem set"]
categories = ["report"]
compiler = "0.14.1"

[template]
path = "template"
entrypoint = "main.typ"
